import React, { useState } from 'react';
import { Zap, ChevronDown, ChevronUp, AlertTriangle, CheckCircle, TrendingUp, Download, RefreshCw } from 'lucide-react';
import ScoreGauge from './ScoreGauge';
import { AnalyzeSkeleton } from './Skeleton';
import { api } from '../hooks/useStreamingText';

const SECTIONS = ['contact', 'summary', 'experience', 'education', 'skills'];
const LS_KEY = 'resume_ai_analyze_result';

function SectionCard({ name, data }) {
  const [open, setOpen] = useState(false);
  const color = data.score >= 8 ? '#68d391' : data.score >= 6 ? '#ed8936' : '#fc8181';
  return (
    <div className="card" style={{ marginBottom: 8, padding: '12px 14px' }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', cursor: 'pointer' }} onClick={() => setOpen(!open)}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{ width: 30, height: 30, borderRadius: 6, background: `${color}20`, display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 700, color, fontSize: 12, flexShrink: 0 }}>{data.score}</div>
          <span style={{ fontWeight: 500, textTransform: 'capitalize', fontSize: 14 }}>{name}</span>
        </div>
        {open ? <ChevronUp size={15} color="#718096" /> : <ChevronDown size={15} color="#718096" />}
      </div>
      {open && <div style={{ marginTop: 10, fontSize: 13, color: '#a0aec0', lineHeight: 1.6 }}>{data.feedback}</div>}
    </div>
  );
}

function exportReport(result) {
  const lines = [
    '# Resume Analysis Report',
    '',
    `## Scores`,
    `- Overall Score: ${result.overall_score}/100`,
    `- ATS Score: ${result.ats_score}/100`,
    result.keyword_match != null ? `- Keyword Match: ${result.keyword_match}/100` : '',
    '',
    `## Summary`,
    result.summary,
    '',
    `## Strengths`,
    ...(result.strengths || []).map(s => `- ${s}`),
    '',
    `## Weaknesses`,
    ...(result.weaknesses || []).map(w => `- ${w}`),
    '',
    `## Top Improvements`,
    ...(result.top_improvements || []).map((t, i) => `${i + 1}. ${t}`),
    '',
    `## Section Scores`,
    ...Object.entries(result.sections || {}).map(([k, v]) => `### ${k}\nScore: ${v.score}/10\n${v.feedback}`),
    '',
    result.missing_keywords?.length > 0 ? `## Missing Keywords\n${result.missing_keywords.join(', ')}` : '',
    '',
    `---`,
    `Generated by Resume AI Assistant · ${new Date().toLocaleDateString()}`,
  ].filter(l => l !== undefined);
  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `resume-analysis-${new Date().toISOString().slice(0, 10)}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function AnalyzeTab({ resumeText, isMobile }) {
  const [jobDesc, setJobDesc] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(() => {
    try { return JSON.parse(localStorage.getItem(LS_KEY)); } catch { return null; }
  });
  const [error, setError] = useState('');
  const [cached, setCached] = useState(() => !!localStorage.getItem(LS_KEY));

  const analyze = async () => {
    if (!resumeText) { setError('Please upload a resume first.'); return; }
    setLoading(true); setError(''); setResult(null); setCached(false);
    try {
      const { data } = await api.post('/analyze', { resume_text: resumeText, job_description: jobDesc || null });
      setResult(data);
      localStorage.setItem(LS_KEY, JSON.stringify(data));
    } catch (e) {
      setError(e.response?.data?.detail || 'Analysis failed. Check your API key and server.');
    } finally {
      setLoading(false);
    }
  };

  const gaugeSize = isMobile ? 85 : 110;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
      <div className="card">
        <div style={{ fontWeight: 600, marginBottom: 10, fontSize: 14 }}>Job Description (Optional)</div>
        <textarea className="input" value={jobDesc} onChange={e => setJobDesc(e.target.value)}
          placeholder="Paste the job description for tailored analysis and keyword matching..."
          style={{ minHeight: isMobile ? 80 : 100 }} />
        <div style={{ marginTop: 12, display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
          <button className="btn-primary" onClick={analyze} disabled={loading || !resumeText}>
            {loading ? <><span className="spinner" style={{ display: 'inline-block', width: 15, height: 15, border: '2px solid #fff3', borderTopColor: '#fff', borderRadius: '50%' }} /> Analyzing...</> : <><Zap size={15} /> Analyze Resume</>}
          </button>
          {error && <button className="btn-secondary" onClick={analyze} style={{ fontSize: 13 }}><RefreshCw size={13} /> Retry</button>}
        </div>
        {error && <div style={{ color: '#fc8181', fontSize: 13, marginTop: 10 }}>{error}</div>}
      </div>

      {loading && <AnalyzeSkeleton isMobile={isMobile} />}

      {result && !loading && (
        <div className="fade-in">
          {cached && (
            <div style={{ fontSize: 12, color: '#718096', background: '#1a1d27', border: '1px solid #2d3748', borderRadius: 8, padding: '8px 12px', marginBottom: 12, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span>Cached result.</span>
              <button onClick={analyze} style={{ background: 'none', border: 'none', color: '#667eea', fontSize: 12, cursor: 'pointer' }}>Refresh</button>
            </div>
          )}

          <div className="card" style={{ marginBottom: 14 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14, flexWrap: 'wrap', gap: 8 }}>
              <div style={{ fontWeight: 700, fontSize: 16 }}>Overall Analysis</div>
              <button className="btn-secondary" onClick={() => exportReport(result)} style={{ padding: '6px 12px', fontSize: 12 }}>
                <Download size={13} /> Export
              </button>
            </div>
            <div style={{ display: 'flex', gap: isMobile ? 12 : 24, flexWrap: 'wrap', justifyContent: 'center', marginBottom: 14 }}>
              <ScoreGauge score={result.overall_score} label="Overall" size={gaugeSize} />
              <ScoreGauge score={result.ats_score} label="ATS Score" size={gaugeSize} />
              {result.keyword_match != null && <ScoreGauge score={result.keyword_match} label="Keywords" size={gaugeSize} />}
            </div>
            <p style={{ color: '#a0aec0', lineHeight: 1.7, fontSize: 13 }}>{result.summary}</p>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 14, marginBottom: 14 }}>
            <div className="card">
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10, fontWeight: 600, color: '#68d391', fontSize: 14 }}>
                <CheckCircle size={15} /> Strengths
              </div>
              <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
                {result.strengths?.map((s, i) => (
                  <li key={i} style={{ fontSize: 13, color: '#a0aec0', paddingLeft: 12, borderLeft: '2px solid #68d391' }}>{s}</li>
                ))}
              </ul>
            </div>
            <div className="card">
              <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10, fontWeight: 600, color: '#fc8181', fontSize: 14 }}>
                <AlertTriangle size={15} /> Weaknesses
              </div>
              <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 8 }}>
                {result.weaknesses?.map((w, i) => (
                  <li key={i} style={{ fontSize: 13, color: '#a0aec0', paddingLeft: 12, borderLeft: '2px solid #fc8181' }}>{w}</li>
                ))}
              </ul>
            </div>
          </div>

          <div className="card" style={{ marginBottom: 14 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10, fontWeight: 600, color: '#7f9cf5', fontSize: 14 }}>
              <TrendingUp size={15} /> Top Improvements
            </div>
            {result.top_improvements?.map((item, i) => (
              <div key={i} style={{ display: 'flex', gap: 10, marginBottom: 10 }}>
                <div style={{ width: 22, height: 22, borderRadius: '50%', background: 'rgba(102,126,234,0.2)', color: '#7f9cf5', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 700, flexShrink: 0 }}>{i + 1}</div>
                <p style={{ fontSize: 13, color: '#a0aec0', lineHeight: 1.6 }}>{item}</p>
              </div>
            ))}
          </div>

          <div className="card" style={{ marginBottom: 14 }}>
            <div style={{ fontWeight: 600, marginBottom: 10, fontSize: 14 }}>Section Scores</div>
            {SECTIONS.map(s => result.sections?.[s] && <SectionCard key={s} name={s} data={result.sections[s]} />)}
          </div>

          {result.missing_keywords?.length > 0 && (
            <div className="card">
              <div style={{ fontWeight: 600, marginBottom: 10, fontSize: 14 }}>Missing Keywords</div>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                {result.missing_keywords.map((k, i) => <span key={i} className="badge badge-red">{k}</span>)}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
